version:                        '2'

services:
  postgres:
    image:                      postgres:10.1
    environment:
      POSTGRES_ROOT_PASSWORD:   testingtesting123
      POSTGRES_DB:              sqlwriter
      POSTGRES_USER:            admin
      POSTGRES_PASSWORD:        testingtesting123
      POSTGRES_PORT:            5432
      SQLWRITER_RUNAS_POSTGRES: 1
    ports:
    - "5432:5432"

  mysql:
    image:                      mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:      testingtesting123
      MYSQL_DATABASE:           sqlwriter
      MYSQL_USER:               admin
      MYSQL_PASSWORD:           testingtesting123
      MYSQL_PORT:               3306
      SQLWRITER_RUNAS_MYSQL:    1
    ports:
    - "3306:3306"
  oracle:
    image:                      estenssoros/oracle_db:12.2.0.1-se2
    environment:
      ORACLE_SID:               ORCLCDB
      ORACLE_PDB:               ORCLPDB1
      ORACLE_PWD:               testingtesting123
      ORACLE_CHARACTERSET:      AL32UTF8
    ports:
    - "1521:1521"
